export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";

export const SET_CURRENT_EDITING = "SET_CURRENT_EDITING";
export const SET_CURRENT_EDITING_TEXT = "SET_CURRENT_EDITING_TEXT";
export const SET_CURRENT_TEXT = "SET_CURRENT_TEXT";

export const APP_LOAD = "APP_LOAD";
export const HOME_PAGE_LOADED = "HOME_PAGE_LOADED";
export const HOME_PAGE_UNLOADED = "HOME_PAGE_UNLOADED";
export const LOGIN = "LOGIN";
export const LOGIN_PAGE_UNLOADED = "LOGIN_PAGE_UNLOADED";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const REGISTER_PAGE_UNLOADED = "REGISTER_PAGE_UNLOADED";
export const UPDATE_FIELD_AUTH = "UPDATE_FIELD_AUTH";

export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";

export const APPLY_ACTIVE_FILTER = "APPLY_ACTIVE_FILTER";
export const APPLY_ALL_FILTER = "APPLY_ALL_FILTER";
export const APPLY_COMPLETED_FILTER = "APPLY_COMPLETED_FILTER";
export const SET_PAGE = "SET_PAGE";
